### ISSUE TITLE
Doesn't work w/ my setup

### ISSUE THREAD

**Issue by CamJN** [seattlerb/minitest-bisect#7]
I usually run my tests with `rake test` and `ruby  -Itest ./test/integration/project_authentication_test.rb` runs the tests, which exhibit the failure. Then `~/.rbenv/shims/minitest_bisect  -Itest test/controllers/subscriptions_controller_test.rb` just says `Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.`

running with `MTB_VERBOSE=2` gives:
```
MTB_VERBOSE=2 ~/.rbenv/shims/minitest_bisect  -Itest test/controllers/subscriptions_controller_test.rb  --seed 58197
reproducing...

/Users/camdennarzt/.rbenv/versions/2.2.2/bin/ruby -Itest -e 'require "./test/controllers/subscriptions_controller_test.rb"' -- --seed 58197 --server 65235

Run options: --seed 58197 --server 65235

# Running:

.........................................................................F/Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1718:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1787:in `to_id'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1103:in `initialize'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:650:in `new'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:650:in `make_proxy'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:567:in `rescue in dump'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:564:in `dump'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:611:in `block in send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:610:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:610:in `send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:925:in `send_request'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1253:in `send_message'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1142:in `block (2 levels) in method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1229:in `open'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1141:in `block in method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1160:in `with_friend'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:1140:in `method_missing'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-server-1.0.2/lib/minitest/server_plugin.rb:37:in `record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:633:in `block in record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:632:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:632:in `record'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:306:in `run_one_method'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:294:in `block (2 levels) in run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:293:in `each'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:293:in `block in run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:332:in `on_signal'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:319:in `with_info_handler'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:292:in `run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `block in __run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `map'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:155:in `__run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:129:in `run'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-5.7.0/lib/minitest.rb:56:in `block in autorun'
Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.
```

and `ruby -Itest -d -S minitest_bisect test/controllers/subscriptions_controller_test.rb` 
gives: 
```
Exception `LoadError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:1222 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems.rb:1231 - cannot load such file -- rubygems/defaults/ruby
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa37108b8a0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371099a90>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa3710a3ef0>
Exception `NoMethodError' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:1984 - undefined method `to_ary' for #<Gem::Specification:0x007fa371112210>
Exception `DRb::DRbBadScheme' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:825 - drbunix:/var/folders/0x/gvllnpys5p9cngslb8r5pnq80000gn/T/minitest.77932
Exception `DRb::DRbBadScheme' at /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/2.2.0/drb/drb.rb:825 - drbunix:/var/folders/0x/gvllnpys5p9cngslb8r5pnq80000gn/T/minitest.77932
reproducing...
Reproduction run passed? Aborting. Try running with MTB_VERBOSE=2 to verify.
```

**Comment by zenspider** [comment]
I don't have diagnostic tools for this kind of setup yet so I can't readily point you at anything to easily say what's wrong.

As a first step, can you install `minitest-autotest` and run:

```
autotest -Itest test/controllers/subscriptions_controller_test.rb
```

If that runs, then I think we can rule out generic DRb issues.

**Comment by CamJN** [comment]
```
$ gem update
[...]
$ gem install minitest-autotest
Fetching: minitest-autotest-1.0.1.gem (100%)
Successfully installed minitest-autotest-1.0.1
1 gem installed
$ autotest -Itest test/controllers/subscriptions_controller_test.rb
/Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/lib/autotest.rb:86:in `parse_options': invalid option: -Itest (OptionParser::InvalidOption)
	from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-autotest-1.0.1/bin/autotest:5:in `<top (required)>'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/bin/autotest:23:in `load'
	from /Users/camdennarzt/.rbenv/versions/2.2.2/bin/autotest:23:in `<main>'
```

**Comment by CamJN** [comment]
Without `-Itest` I get
```
autotest test/controllers/subscriptions_controller_test.rb
/Users/camdennarzt/.rbenv/versions/2.2.2/bin/ruby -I.:lib:test -rubygems -e "gem 'minitest'; %w[minitest/autorun test/controllers/subscriptions_controller_test.rb].each { |f| require f }" -- --server 49302

invalid option: --server

minitest options:
    -h, --help                       Display this help.
    -s, --seed SEED                  Sets random seed. Also via env. Eg: SEED=n rake
    -v, --verbose                    Verbose. Show progress processing files.
    -n, --name PATTERN               Filter run on /regexp/ or string.

Known extensions: pride
    -p, --pride                      Pride. Show your testing pride!
```

**Comment by zenspider** [comment]
Hrm. Something odd is going on. From your previous stack trace:

```
    from /Users/camdennarzt/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/minitest-server-1.0.2/lib/minitest/server_plugin.rb:37:in `record'
```

So you have minitest-server installed and being used in 2.2.2. What version of minitest + minitest-server + minitest-autotest are you trying to use? Maybe there's some wierd combo that doesn't get along.

**Comment by CamJN** [comment]
All minitest gems w/ versions:

minitest (5.7.0)
minitest-autotest (1.0.1)
minitest-bisect (1.3.0)
minitest-byebug (0.0.3)
minitest-server (1.0.2)

**Comment by zenspider** [comment]
This is... a stumper. I'm honestly not sure how to proceed w/o digging into your code and hacking on stuff. It _looks_ like you're not getting all the plugins loaded, but why that would be I have no idea.

Is there any way I can reproduce this on my end?

**Comment by zenspider** [comment]
Anything?

**Comment by zenspider** [comment]
I can't do anything without feedback and information...

**Comment by CamJN** [comment]
I'm sorry but I don't know what to tell you, I am running on OS X 10.10, I got rbenv from homebrew and built ruby from rbenv. The app I was trying to debug is a very vanilla rails app.

If there's some info you think would help I'll provide it, but I don't know what's wrong.

**Comment by fighella** [comment]
Same issue for me. 
ruby/2.0.0/drb/drb.rb:1687:in `current_server': DRb::DRbServerNotFound (DRb::DRbConnError)

**Comment by zenspider** [comment]
@fighella sorry for dropping the ball here. can you still repro this? If so, any chance you can give me your current environment / setup such that I might figure out how to repro on my side? Looks like we're all on osx and using ruby 2.x.

**Comment by jsparling** [comment]
@zenspider, @fighella and @CamJN,
I was getting the "invalid option: --server" error. I added minitest-bisect to my Gemfile, ran 'bundle install' and the error went away.

**Comment by zenspider** [comment]
@jsparling can you send in a PR with that tidbit added to an FAQ section of the README?

**Comment by jsparling** [comment]
@zenspider PR: https://github.com/seattlerb/minitest-bisect/pull/11

**Comment by zenspider** [comment]
I think this is handled. Please reopen if it isn't.
